"""initial database schema

Revision ID: 453be70581b9
Revises:
Create Date: 2026-07-21 19:23:09.140459

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "453be70581b9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "school_classes",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "system_settings",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("max_pending_requests", sa.Integer(), nullable=False),
        sa.Column("reopen_threshold", sa.Integer(), nullable=False),
        sa.Column("planning_window_days", sa.Integer(), nullable=False),
        sa.Column("booking_queue_locked", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("id = 1", name="ck_system_settings_single_row"),
        sa.CheckConstraint(
            "max_pending_requests > 0",
            name="ck_system_settings_max_pending_positive",
        ),
        sa.CheckConstraint(
            "reopen_threshold >= 0",
            name="ck_system_settings_reopen_nonnegative",
        ),
        sa.CheckConstraint(
            "reopen_threshold < max_pending_requests",
            name="ck_system_settings_reopen_below_max",
        ),
        sa.CheckConstraint(
            "planning_window_days > 0",
            name="ck_system_settings_window_positive",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN",
                "SCHEDULER",
                "TEACHER",
                "MONITOR",
                name="user_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "class_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(role = 'MONITOR' AND class_id IS NOT NULL) OR "
            "(role <> 'MONITOR' AND class_id IS NULL)",
            name="ck_user_monitor_class",
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["school_classes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "audit_logs",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "actor_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column(
            "entity_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_logs_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "booking_requests",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "requester_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "class_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "teacher_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=120), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "HIGH",
                "NORMAL",
                name="request_priority",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SCHEDULED",
                "REJECTED",
                "CANCELLED",
                name="request_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["school_classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("booking_requests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_booking_request_queue",
            ["status", "priority", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_booking_requests_class_id"), ["class_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_booking_requests_requester_id"),
            ["requester_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_booking_requests_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_booking_requests_teacher_id"), ["teacher_id"], unique=False
        )

    op.create_table(
        "room_blocks",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("block_date", sa.Date(), nullable=False),
        sa.Column(
            "scope",
            sa.Enum(
                "SLOT",
                "ROOM_DAY",
                "DAY",
                name="block_scope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "room_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "prep",
            sa.Enum(
                "PREP_1",
                "PREP_2",
                name="prep_period",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_by_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "removed_by_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "(scope = 'SLOT' AND room_id IS NOT NULL AND prep IS NOT NULL) OR "
            "(scope = 'ROOM_DAY' AND room_id IS NOT NULL AND prep IS NULL) OR "
            "(scope = 'DAY' AND room_id IS NULL AND prep IS NULL)",
            name="ck_room_block_scope",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["removed_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("room_blocks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_room_blocks_block_date"), ["block_date"], unique=False
        )

    op.create_table(
        "notifications",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "user_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "APPROVED",
                "REJECTED",
                "RESCHEDULED",
                "CANCELLED",
                "PASSWORD_RESET",
                "SYSTEM",
                name="notification_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "booking_request_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_request_id"],
            ["booking_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "scheduled_bookings",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column(
            "request_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("schedule_date", sa.Date(), nullable=False),
        sa.Column(
            "prep",
            sa.Enum(
                "PREP_1",
                "PREP_2",
                name="prep_period",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "room_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "class_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "teacher_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "scheduled_by_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["school_classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["booking_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    with op.batch_alter_table("scheduled_bookings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scheduled_bookings_schedule_date"),
            ["schedule_date"],
            unique=False,
        )
        batch_op.create_index(
            "uq_active_class_slot",
            ["schedule_date", "prep", "class_id"],
            unique=True,
            postgresql_where=sa.text("is_active = true"),
            sqlite_where=sa.text("is_active = 1"),
        )
        batch_op.create_index(
            "uq_active_room_slot",
            ["schedule_date", "prep", "room_id"],
            unique=True,
            postgresql_where=sa.text("is_active = true"),
            sqlite_where=sa.text("is_active = 1"),
        )
        batch_op.create_index(
            "uq_active_teacher_slot",
            ["schedule_date", "prep", "teacher_id"],
            unique=True,
            postgresql_where=sa.text("is_active = true"),
            sqlite_where=sa.text("is_active = 1"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scheduled_bookings", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_active_teacher_slot",
            postgresql_where=sa.text("is_active = true"),
            sqlite_where=sa.text("is_active = 1"),
        )
        batch_op.drop_index(
            "uq_active_room_slot",
            postgresql_where=sa.text("is_active = true"),
            sqlite_where=sa.text("is_active = 1"),
        )
        batch_op.drop_index(
            "uq_active_class_slot",
            postgresql_where=sa.text("is_active = true"),
            sqlite_where=sa.text("is_active = 1"),
        )
        batch_op.drop_index(batch_op.f("ix_scheduled_bookings_schedule_date"))

    op.drop_table("scheduled_bookings")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("room_blocks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_room_blocks_block_date"))

    op.drop_table("room_blocks")
    with op.batch_alter_table("booking_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_booking_requests_teacher_id"))
        batch_op.drop_index(batch_op.f("ix_booking_requests_status"))
        batch_op.drop_index(batch_op.f("ix_booking_requests_requester_id"))
        batch_op.drop_index(batch_op.f("ix_booking_requests_class_id"))
        batch_op.drop_index("ix_booking_request_queue")

    op.drop_table("booking_requests")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    op.drop_table("system_settings")
    op.drop_table("school_classes")
    op.drop_table("rooms")
    # ### end Alembic commands ###
